name: autofix.ci

on:
  push:
  pull_request:

jobs:
  autofix:
    name: Auto Fix
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Cargo Format
        uses: yonasBSD/toolkit@7757e45441401d468ec049000c61571426a47de4 # v1.0.0
        with:
          run: |
            cargo format

      - name: Autofix
        uses: autofix-ci/action@7a166d7532b277f34e16238930461bf77f9d7ed8
        with:
          commit-message: "fix(ci): [autofix.ci] apply automated fixes"
